server:
  port: 443
  ssl:
    key-store: keystore.p12
    key-store-password: secretpassword
    keyStoreType: PKCS12
    keyAlias: tomcat
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/spellbook
    username: postgres
    password: postgres
  jooq:
    sql-dialect: Postgres
  liquibase:
    enabled: true
    change-log: classpath:/root-changelog.xml
spellbook:
  username: user
  password: password
  allowedIp: 127.0.0.1